<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class FollowerPositionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $positions = [
            // Church - Pastoral & Spiritual Leadership
            [
                'name' => 'Senior Pastor / Lead Pastor',
                'slug' => 'senior-pastor-lead-pastor',
                'description' => 'Primary spiritual leader and preacher of the church',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Associate Pastor',
                'slug' => 'associate-pastor',
                'description' => 'Supports senior pastor in various ministerial duties',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Youth Pastor',
                'slug' => 'youth-pastor',
                'description' => 'Leads youth ministry and discipleship programs',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Worship Pastor / Minister of Music',
                'slug' => 'worship-pastor-minister-music',
                'description' => 'Leads worship services and music ministry',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Children\'s Pastor',
                'slug' => 'childrens-pastor',
                'description' => 'Oversees children\'s ministry and programs',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Teaching Pastor',
                'slug' => 'teaching-pastor',
                'description' => 'Focuses on biblical teaching and discipleship',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Evangelism Pastor',
                'slug' => 'evangelism-pastor',
                'description' => 'Leads outreach and evangelism efforts',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Missions Pastor',
                'slug' => 'missions-pastor',
                'description' => 'Coordinates local and international missions',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Bishop',
                'slug' => 'bishop',
                'description' => 'Senior ecclesiastical leader in denominational structure',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Apostle',
                'slug' => 'apostle',
                'description' => 'Foundational ministry role with broad oversight',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Overseer',
                'slug' => 'overseer',
                'description' => 'Provides spiritual oversight to multiple churches or ministries',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Elder',
                'slug' => 'elder',
                'description' => 'Spiritual leader providing guidance and oversight',
                'category' => 'church_pastoral',
                'is_active' => true,
                'sort_order' => 12,
            ],

            // Church - Ministry Roles
            [
                'name' => 'Deacon / Deaconess',
                'slug' => 'deacon-deaconess',
                'description' => 'Serves in practical ministry and church operations',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Minister',
                'slug' => 'minister',
                'description' => 'Ordained clergy serving in various capacities',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Church Administrator',
                'slug' => 'church-administrator',
                'description' => 'Manages church operations and administration',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Worship Leader',
                'slug' => 'worship-leader',
                'description' => 'Leads congregational worship during services',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Choir Director',
                'slug' => 'choir-director',
                'description' => 'Directs church choir and vocal ensembles',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Musicians',
                'slug' => 'musicians',
                'description' => 'Plays instruments for worship services (Keyboardist, Drummer, Guitarist, etc.)',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Prayer Team Leader',
                'slug' => 'prayer-team-leader',
                'description' => 'Leads prayer ministry and intercession teams',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Usher Team Leader',
                'slug' => 'usher-team-leader',
                'description' => 'Oversees usher team and service logistics',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Hospitality Coordinator',
                'slug' => 'hospitality-coordinator',
                'description' => 'Coordinates guest services and church hospitality',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Christian Education Director',
                'slug' => 'christian-education-director',
                'description' => 'Oversees educational programs and discipleship',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'Sunday School Superintendent',
                'slug' => 'sunday-school-superintendent',
                'description' => 'Manages Sunday school program and teachers',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'Bible Study Teacher',
                'slug' => 'bible-study-teacher',
                'description' => 'Leads Bible study groups and teaching sessions',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'Outreach Coordinator',
                'slug' => 'outreach-coordinator',
                'description' => 'Coordinates community outreach and evangelism events',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'Media Ministry Leader',
                'slug' => 'media-ministry-leader',
                'description' => 'Oversees media production and presentation',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'Sound Engineer',
                'slug' => 'sound-engineer',
                'description' => 'Manages audio equipment and sound quality',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'Livestream / Tech Ministry Lead',
                'slug' => 'livestream-tech-ministry-lead',
                'description' => 'Manages online streaming and technology services',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 28,
            ],
            [
                'name' => 'Church Counselor',
                'slug' => 'church-counselor',
                'description' => 'Provides biblical counseling and spiritual guidance',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Youth Ministry Coordinator',
                'slug' => 'youth-ministry-coordinator',
                'description' => 'Coordinates youth programs and activities',
                'category' => 'church_ministry',
                'is_active' => true,
                'sort_order' => 30,
            ],

            // Church - Operational & Support Roles
            [
                'name' => 'Executive Assistant',
                'slug' => 'executive-assistant',
                'description' => 'Supp pastoral staff with administrative tasks',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'name' => 'Finance Director',
                'slug' => 'finance-director',
                'description' => 'Manages church finances and budgeting',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'name' => 'Treasurer',
                'slug' => 'treasurer',
                'description' => 'Oversees church funds and financial reporting',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'Bookkeeper',
                'slug' => 'bookkeeper',
                'description' => 'Handles day-to-day financial transactions',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Event Coordinator',
                'slug' => 'event-coordinator',
                'description' => 'Plans and coordinates church events',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 35,
            ],
            [
                'name' => 'Volunteer Coordinator',
                'slug' => 'volunteer-coordinator',
                'description' => 'Recruits and manages church volunteers',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 36,
            ],
            [
                'name' => 'Facilities Manager',
                'slug' => 'facilities-manager',
                'description' => 'Manages church building and maintenance',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 37,
            ],
            [
                'name' => 'Security Team Leader',
                'slug' => 'security-team-leader',
                'description' => 'Oversees church security and safety protocols',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 38,
            ],
            [
                'name' => 'Transportation Coordinator',
                'slug' => 'transportation-coordinator',
                'description' => 'Coordinates church transportation needs',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 39,
            ],
            [
                'name' => 'Communications / Social Media Manager',
                'slug' => 'communications-social-media-manager',
                'description' => 'Manages church communications and social media',
                'category' => 'church_operations',
                'is_active' => true,
                'sort_order' => 40,
            ],

            // Church - Faith-Based & Community Leadership
            [
                'name' => 'Intercessor',
                'slug' => 'intercessor',
                'description' => 'Devoted to prayer and intercession for the church',
                'category' => 'church_community',
                'is_active' => true,
                'sort_order' => 41,
            ],
            [
                'name' => 'Missionary',
                'slug' => 'missionary',
                'description' => 'Serves in cross-cultural or international ministry',
                'category' => 'church_community',
                'is_active' => true,
                'sort_order' => 42,
            ],
            [
                'name' => 'Community Chaplain',
                'slug' => 'community-chaplain',
                'description' => 'Provides spiritual care in community settings',
                'category' => 'church_community',
                'is_active' => true,
                'sort_order' => 43,
            ],
            [
                'name' => 'Church Mother / Church Father',
                'slug' => 'church-mother-father',
                'description' => 'Elder providing spiritual guidance and wisdom',
                'category' => 'church_community',
                'is_active' => true,
                'sort_order' => 44,
            ],
            [
                'name' => 'Pastoral Care Team Member',
                'slug' => 'pastoral-care-team-member',
                'description' => 'Provides care and support to congregation members',
                'category' => 'church_community',
                'is_active' => true,
                'sort_order' => 45,
            ],

            // Nonprofit - Executive Leadership
            [
                'name' => 'Chief Executive Officer (CEO)',
                'slug' => 'chief-executive-officer',
                'description' => 'Top executive responsible for overall leadership',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 46,
            ],
            [
                'name' => 'Executive Director',
                'slug' => 'executive-director',
                'description' => 'Senior staff leader reporting to the board',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 47,
            ],
            [
                'name' => 'Chief Operating Officer (COO)',
                'slug' => 'chief-operating-officer',
                'description' => 'Oversees daily operations and administration',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 48,
            ],
            [
                'name' => 'Chief Financial Officer (CFO)',
                'slug' => 'chief-financial-officer',
                'description' => 'Manages financial strategy and operations',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 49,
            ],
            [
                'name' => 'Chief Program Officer (CPO)',
                'slug' => 'chief-program-officer',
                'description' => 'Oversees program development and delivery',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'name' => 'Chief Development Officer (CDO)',
                'slug' => 'chief-development-officer',
                'description' => 'Leads fundraising and development strategy',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 51,
            ],
            [
                'name' => 'Board Chair / Board President',
                'slug' => 'board-chair-president',
                'description' => 'Leads the board of directors',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 52,
            ],
            [
                'name' => 'Board Vice Chair',
                'slug' => 'board-vice-chair',
                'description' => 'Supports board chair and assumes duties when absent',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 53,
            ],
            [
                'name' => 'Board Treasurer',
                'slug' => 'board-treasurer',
                'description' => 'Oversees financial oversight on the board',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 54,
            ],
            [
                'name' => 'Board Secretary',
                'slug' => 'board-secretary',
                'description' => 'Manages board records and documentation',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 55,
            ],
            [
                'name' => 'Board Members',
                'slug' => 'board-members',
                'description' => 'Governance and oversight volunteers',
                'category' => 'nonprofit_executive',
                'is_active' => true,
                'sort_order' => 56,
            ],

            // Nonprofit - Program & Service Delivery
            [
                'name' => 'Program Director',
                'slug' => 'program-director',
                'description' => 'Oversees specific program areas and initiatives',
                'category' => 'nonprofit_programs',
                'is_active' => true,
                'sort_order' => 57,
            ],
            [
                'name' => 'Program Manager',
                'slug' => 'program-manager',
                'description' => 'Manages program implementation and staff',
                'category' => 'nonprofit_programs',
                'is_active' => true,
                'sort_order' => 58,
            ],
            [
                'name' => 'Program Coordinator',
                'slug' => 'program-coordinator',
                'description' => 'Coordinates program activities and logistics',
                'category' => 'nonprofit_programs',
                'is_active' => true,
                'sort_order' => 59,
            ],
            [
                'name' => 'Case Manager',
                'slug' => 'case-manager',
                'description' => 'Manages individual client cases and services',
                'category' => 'nonprofit_programs',
                'is_active' => true,
                'sort_order' => 60,
            ],
            [
                'name' => 'Social Worker',
                'slug' => 'social-worker',
                'description' => 'Provides social services and client support',
                'category' => 'nonprofit_programs',
                'is_active' => true,
                'sort_order' => 61,
            ],
            [
                'name' => 'Community Outreach Specialist',
                'slug' => 'community-outreach-specialist',
                'description' => 'Engages community and promotes services',
                'category' => 'nonprofit_programs',
                'is_active' => true,
                'sort_order' => 62,
            ],
            [
                'name' => 'Education Specialist',
                'slug' => 'education-specialist',
                'description' => 'Develops and delivers educational programs',
                'category' => 'nonprofit_programs',
                'is_active' => true,
                'sort_order' => 63,
            ],
            [
                'name' => 'Trainer / Facilitator',
                'slug' => 'trainer-facilitator',
                'description' => 'Leads training sessions and workshops',
                'category' => 'nonprofit_programs',
                'is_active' => true,
                'sort_order' => 64,
            ],
            [
                'name' => 'Counselor',
                'slug' => 'counselor',
                'description' => 'Provides professional counseling services',
                'category' => 'nonprofit_programs',
                'is_active' => true,
                'sort_order' => 65,
            ],

            // Nonprofit - Development & Fundraising
            [
                'name' => 'Development Director',
                'slug' => 'development-director',
                'description' => 'Leads fundraising and development efforts',
                'category' => 'nonprofit_fundraising',
                'is_active' => true,
                'sort_order' => 66,
            ],
            [
                'name' => 'Grant Writer',
                'slug' => 'grant-writer',
                'description' => 'Researches and writes grant proposals',
                'category' => 'nonprofit_fundraising',
                'is_active' => true,
                'sort_order' => 67,
            ],
            [
                'name' => 'Fundraising Manager',
                'slug' => 'fundraising-manager',
                'description' => 'Manages fundraising campaigns and events',
                'category' => 'nonprofit_fundraising',
                'is_active' => true,
                'sort_order' => 68,
            ],
            [
                'name' => 'Donor Relations Manager',
                'slug' => 'donor-relations-manager',
                'description' => 'Cultivates and maintains donor relationships',
                'category' => 'nonprofit_fundraising',
                'is_active' => true,
                'sort_order' => 69,
            ],
            [
                'name' => 'Campaign Manager',
                'slug' => 'campaign-manager',
                'description' => 'Manages specific fundraising campaigns',
                'category' => 'nonprofit_fundraising',
                'is_active' => true,
                'sort_order' => 70,
            ],
            [
                'name' => 'Event Fundraising Coordinator',
                'slug' => 'event-fundraising-coordinator',
                'description' => 'Coordinates fundraising events and galas',
                'category' => 'nonprofit_fundraising',
                'is_active' => true,
                'sort_order' => 71,
            ],

            // Nonprofit - Marketing & Communications
            [
                'name' => 'Marketing Director',
                'slug' => 'marketing-director',
                'description' => 'Leads marketing strategy and brand management',
                'category' => 'nonprofit_marketing',
                'is_active' => true,
                'sort_order' => 72,
            ],
            [
                'name' => 'Communications Director',
                'slug' => 'communications-director',
                'description' => 'Oversees internal and external communications',
                'category' => 'nonprofit_marketing',
                'is_active' => true,
                'sort_order' => 73,
            ],
            [
                'name' => 'Social Media Manager',
                'slug' => 'social-media-manager',
                'description' => 'Manages social media presence and content',
                'category' => 'nonprofit_marketing',
                'is_active' => true,
                'sort_order' => 74,
            ],
            [
                'name' => 'Content Creator',
                'slug' => 'content-creator',
                'description' => 'Creates engaging content for various platforms',
                'category' => 'nonprofit_marketing',
                'is_active' => true,
                'sort_order' => 75,
            ],
            [
                'name' => 'Public Relations Manager',
                'slug' => 'public-relations-manager',
                'description' => 'Manages media relations and public image',
                'category' => 'nonprofit_marketing',
                'is_active' => true,
                'sort_order' => 76,
            ],
            [
                'name' => 'Graphic Designer',
                'slug' => 'graphic-designer',
                'description' => 'Creates visual content and brand materials',
                'category' => 'nonprofit_marketing',
                'is_active' => true,
                'sort_order' => 77,
            ],

            // Nonprofit - Operations & Administration
            [
                'name' => 'Operations Manager',
                'slug' => 'operations-manager',
                'description' => 'Manages daily operational functions',
                'category' => 'nonprofit_operations',
                'is_active' => true,
                'sort_order' => 78,
            ],
            [
                'name' => 'HR Manager',
                'slug' => 'hr-manager',
                'description' => 'Oversees human resources and personnel',
                'category' => 'nonprofit_operations',
                'is_active' => true,
                'sort_order' => 79,
            ],
            [
                'name' => 'Office Manager',
                'slug' => 'office-manager',
                'description' => 'Manages office administration and supplies',
                'category' => 'nonprofit_operations',
                'is_active' => true,
                'sort_order' => 80,
            ],
            [
                'name' => 'Administrative Assistant',
                'slug' => 'administrative-assistant',
                'description' => 'Provides administrative support to staff',
                'category' => 'nonprofit_operations',
                'is_active' => true,
                'sort_order' => 81,
            ],
            [
                'name' => 'Finance Manager',
                'slug' => 'finance-manager',
                'description' => 'Manages financial operations and reporting',
                'category' => 'nonprofit_operations',
                'is_active' => true,
                'sort_order' => 82,
            ],
            [
                'name' => 'Accountant / Bookkeeper',
                'slug' => 'accountant-bookkeeper',
                'description' => 'Handles accounting and financial records',
                'category' => 'nonprofit_operations',
                'is_active' => true,
                'sort_order' => 83,
            ],
            [
                'name' => 'Compliance Officer',
                'slug' => 'compliance-officer',
                'description' => 'Ensures regulatory and legal compliance',
                'category' => 'nonprofit_operations',
                'is_active' => true,
                'sort_order' => 84,
            ],
            [
                'name' => 'Risk Management Officer',
                'slug' => 'risk-management-officer',
                'description' => 'Identifies and mitigates organizational risks',
                'category' => 'nonprofit_operations',
                'is_active' => true,
                'sort_order' => 85,
            ],

            // Nonprofit - Technology & Digital Roles
            [
                'name' => 'IT Director',
                'slug' => 'it-director',
                'description' => 'Oversees technology infrastructure and strategy',
                'category' => 'nonprofit_technology',
                'is_active' => true,
                'sort_order' => 86,
            ],
            [
                'name' => 'Web Manager',
                'slug' => 'web-manager',
                'description' => 'Manages website content and functionality',
                'category' => 'nonprofit_technology',
                'is_active' => true,
                'sort_order' => 87,
            ],
            [
                'name' => 'Data Analyst',
                'slug' => 'data-analyst',
                'description' => 'Analyzes organizational data for insights',
                'category' => 'nonprofit_technology',
                'is_active' => true,
                'sort_order' => 88,
            ],
            [
                'name' => 'CRM / Database Administrator',
                'slug' => 'crm-database-administrator',
                'description' => 'Manages donor and constituent database systems',
                'category' => 'nonprofit_technology',
                'is_active' => true,
                'sort_order' => 89,
            ],
            [
                'name' => 'Software Developer',
                'slug' => 'software-developer',
                'description' => 'Develops custom software solutions (if tech-based nonprofit)',
                'category' => 'nonprofit_technology',
                'is_active' => true,
                'sort_order' => 90,
            ],

            // Nonprofit - Volunteer & Community Engagement
            [
                'name' => 'Volunteer Coordinator',
                'slug' => 'volunteer-coordinator-nonprofit',
                'description' => 'Recruits and manages nonprofit volunteers',
                'category' => 'nonprofit_engagement',
                'is_active' => true,
                'sort_order' => 91,
            ],
            [
                'name' => 'Community Engagement Director',
                'slug' => 'community-engagement-director',
                'description' => 'Leads community outreach and partnership efforts',
                'category' => 'nonprofit_engagement',
                'is_active' => true,
                'sort_order' => 92,
            ],
            [
                'name' => 'Partnership Manager',
                'slug' => 'partnership-manager',
                'description' => 'Manages organizational partnerships and collaborations',
                'category' => 'nonprofit_engagement',
                'is_active' => true,
                'sort_order' => 93,
            ],

            // Nonprofit - Faith-Based & Community Leadership
            [
                'name' => 'Minister or Chaplain',
                'slug' => 'minister-chaplain',
                'description' => 'Provides spiritual care (if faith-aligned nonprofit)',
                'category' => 'nonprofit_community',
                'is_active' => true,
                'sort_order' => 94,
            ],
            [
                'name' => 'Community Organizer',
                'slug' => 'community-organizer',
                'description' => 'Mobilizes community for social change',
                'category' => 'nonprofit_community',
                'is_active' => true,
                'sort_order' => 95,
            ],
            [
                'name' => 'Outreach Minister',
                'slug' => 'outreach-minister',
                'description' => 'Leads faith-based outreach initiatives',
                'category' => 'nonprofit_community',
                'is_active' => true,
                'sort_order' => 96,
            ],
            [
                'name' => 'Program Ambassador',
                'slug' => 'program-ambassador',
                'description' => 'Represents and promotes programs in community',
                'category' => 'nonprofit_community',
                'is_active' => true,
                'sort_order' => 97,
            ],
        ];

        foreach ($positions as $position) {
            DB::table('follower_positions')->insert([
                'name' => $position['name'],
                'slug' => $position['slug'],
                'description' => $position['description'],
                'category' => $position['category'],
                'is_active' => $position['is_active'],
                'sort_order' => $position['sort_order'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
