<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PositionCategory;
use App\Models\JobPosition;

class PositionCategoriesAndJobPositionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            'Education & Youth' => [
                'Coordinator Tutor',
                'Mentor',
                'Team Member Reading Assistant',
                'Intern Homework Helper',
                'Support STEM Coach',
                'Support Language Partner',
                'Lead After-School Assistant',
                'Volunteer College Prep Advisor',
                'Coordinator Special Needs Support',
                'Volunteer Virtual Classroom Aid',
                'Assistant Mentor',
                'Assistant Reading Assistant',
                'Team Member Homework Helper',
                'Lead STEM Coach',
                'College Prep Advisor',
                'Coordinator Virtual Classroom Aid',
                'Support Tutor',
                'Volunteer Mentor',
                'Intern Reading Assistant',
                'Lead Homework Helper',
                'Intern STEM Coach',
                'Volunteer Language Partner',
                'Coordinator After-School Assistant',
                'Volunteer College Prep Advisor',
                'Support Special Needs Support',
                'Lead Virtual Classroom Aid',
                'Team Member Tutor',
                'Coordinator Mentor',
                'Volunteer Reading Assistant',
                'Volunteer Homework Helper',
                'Lead STEM Coach',
                'Intern Language Partner',
                'Volunteer After-School Assistant',
                'College Prep Advisor',
                'Volunteer Tutor',
                'Volunteer Mentor',
                'Volunteer Reading Assistant',
                'Team Member Homework Helper',
                'Coordinator STEM Coach',
                'Language Partner',
                'Lead After-School Assistant',
                'Coordinator College Prep Advisor',
                'Volunteer Virtual Classroom Aid',
                'Education & Youth-Other'
            ],
            'Healthcare & Wellness' => [
                'Assistant Hospital Greeter',
                'Clinic Assistant',
                'Assistant Health Workshop Volunteer',
                'Intern Mental Health Peer',
                'Assistant Hospice Companion',
                'Coordinator Wellness Coach',
                'Coordinator Vaccination Site Support',
                'Lead Blood Drive Organizer',
                'Assistant Medical Records Helper',
                'Fitness Program Aide',
                'Volunteer Hospital Greeter',
                'Support Clinic Assistant',
                'Support Health Workshop Volunteer',
                'Lead Hospice Companion',
                'Support Wellness Coach',
                'Intern Vaccination Site Support',
                'Coordinator Blood Drive Organizer',
                'Team Member Medical Records Helper',
                'Intern Fitness Program Aide',
                'Support Hospital Greeter',
                'Intern Clinic Assistant',
                'Lead Health Workshop Volunteer',
                'Volunteer Hospice Companion',
                'Wellness Coach',
                'Support Vaccination Site Support',
                'Volunteer Blood Drive Organizer',
                'Coordinator Medical Records Helper',
                'Lead Fitness Program Aide',
                'Team Member Hospital Greeter',
                'Clinic Assistant',
                'Team Member Health Workshop Volunteer',
                'Mental Health Peer',
                'Support Hospice Companion',
                'Lead Wellness Coach',
                'Team Member Vaccination Site Support',
                'Team Member Blood Drive Organizer',
                'Team Member Medical Records Helper',
                'Assistant Fitness Program Aide',
                'Lead Hospital Greeter',
                'Team Member Clinic Assistant',
                'Intern Health Workshop Volunteer',
                'Assistant Hospice Companion',
                'Medical Records Helper',
                'Fitness Program Aide',
                'Healthcare & Wellness-Other'
            ],
            'Community & Social Impact' => [
                'Intern Food Bank Volunteer',
                'Lead Homeless Shelter Assistant',
                'Lead Crisis Line Operator',
                'Intern Community Organizer',
                'Support Voter Registration Volunteer',
                'Volunteer Senior Companion',
                'Assistant Neighborhood Watch Volunteer',
                'Disaster Relief Worker',
                'Lead Refugee Support',
                'Support Meal Delivery Driver',
                'Team Member Homeless Shelter Assistant',
                'Volunteer Crisis Line Operator',
                'Assistant Voter Registration Volunteer',
                'Lead Senior Companion',
                'Intern Disaster Relief Worker',
                'Refugee Support',
                'Lead Meal Delivery Driver',
                'Food Bank Volunteer',
                'Volunteer Crisis Line Operator',
                'Community Organizer',
                'Intern Senior Companion',
                'Neighborhood Watch Volunteer',
                'Disaster Relief Worker',
                'Volunteer Meal Delivery Driver',
                'Coordinator Homeless Shelter Assistant',
                'Lead Community Organizer',
                'Lead Voter Registration Volunteer',
                'Lead Neighborhood Watch Volunteer',
                'Lead Disaster Relief Worker',
                'Coordinator Meal Delivery Driver',
                'Community & Social Impact-Other'
            ],
            'Environmental & Animal Care' => [
                'Assistant Park Cleanup Crew',
                'Team Member Tree Planter',
                'Lead Beach Cleanup Leader',
                'Team Member Wildlife Conservationist',
                'Team Member Animal Shelter Assistant',
                'Volunteer Pet Foster Coordinator',
                'Lead Sustainability Educator',
                'Assistant Zoo Volunteer',
                'Recycling Program Helper',
                'Assistant Eco Workshop Organizer',
                'Intern Park Cleanup Crew',
                'Coordinator Beach Cleanup Leader',
                'Intern Wildlife Conservationist',
                'Pet Foster Coordinator',
                'Support Sustainability Educator',
                'Intern Zoo Volunteer',
                'Coordinator Recycling Program Helper',
                'Team Member Eco Workshop Organizer',
                'Volunteer Park Cleanup Crew',
                'Tree Planter',
                'Team Member Beach Cleanup Leader',
                'Volunteer Wildlife Conservationist',
                'Coordinator Sustainability Educator',
                'Support Zoo Volunteer',
                'Recycling Program Helper',
                'Support Eco Workshop Organizer',
                'Coordinator Park Cleanup Crew',
                'Assistant Tree Planter',
                'Volunteer Beach Cleanup Leader',
                'Assistant Wildlife Conservationist',
                'Coordinator Pet Foster Coordinator',
                'Assistant Sustainability Educator',
                'Support Zoo Volunteer',
                'Eco Workshop Organizer',
                'Environmental & Animal Care-Other'
            ],
            'Arts, Media & Tech' => [
                'Volunteer Graphic Design Volunteer',
                'Team Member Social Media Assistant',
                'Support Web Developer',
                'Intern Content Writer',
                'Coordinator Event Photographer',
                'Podcast Editor',
                'Lead Video Creator',
                'Volunteer Digital Archivist',
                'Coordinator IT Support Volunteer',
                'Volunteer Online Event Host',
                'Graphic Design Volunteer',
                'Intern Social Media Assistant',
                'Lead Web Developer',
                'Coordinator Content Writer',
                'Podcast Editor',
                'Coordinator Video Creator',
                'Digital Archivist',
                'Lead IT Support Volunteer',
                'Graphic Design Volunteer',
                'Social Media Assistant',
                'Intern Web Developer',
                'Support Content Writer',
                'Team Member Event Photographer',
                'Assistant Video Creator',
                'Volunteer IT Support Volunteer',
                'Assistant Online Event Host',
                'Lead Graphic Design Volunteer',
                'Lead Social Media Assistant',
                'Lead Content Writer',
                'Team Member Podcast Editor',
                'Intern Video Creator',
                'Team Member Digital Archivist',
                'Team Member IT Support Volunteer',
                'Support Online Event Host',
                'Arts, Media & Tech-Other'
            ],
            'Admin & Office Support' => [
                'Coordinator Data Entry Volunteer',
                'Coordinator Reception Assistant',
                'Lead Mailing Assistant',
                'Intern Fundraising Caller',
                'Volunteer Event Planner Assistant',
                'Intern Research Assistant',
                'Coordinator Grant Writer',
                'Support Survey Collector',
                'Intern Translator',
                'Volunteer Document Organizer',
                'Volunteer Data Entry Volunteer',
                'Support Reception Assistant',
                'Volunteer Fundraising Caller',
                'Team Member Event Planner Assistant',
                'Coordinator Research Assistant',
                'Volunteer Grant Writer',
                'Volunteer Survey Collector',
                'Lead Translator',
                'Support Document Organizer',
                'Team Member Reception Assistant',
                'Mailing Assistant',
                'Team Member Fundraising Caller',
                'Assistant Event Planner Assistant',
                'Lead Research Assistant',
                'Survey Collector',
                'Intern Translator',
                'Reception Assistant',
                'Support Fundraising Caller',
                'Lead Event Planner Assistant',
                'Assistant Research Assistant',
                'Lead Grant Writer',
                'Team Member Translator',
                'Admin & Office Support-Other'
            ],
            'Faith-Based & Mission Work' => [
                'Support Church Usher',
                'Support Mission Trip Volunteer',
                'Volunteer Youth Group Leader',
                'Coordinator Bible Study Assistant',
                'Support Community Prayer Partner',
                'Assistant Church Tech Support',
                'Lead Sunday School Teacher',
                'Support Choir Assistant',
                'Coordinator Faith-Based Outreach Worker',
                'Clothing Drive Volunteer',
                'Church Usher',
                'Volunteer Mission Trip Volunteer',
                'Intern Youth Group Leader',
                'Assistant Community Prayer Partner',
                'Support Church Tech Support',
                'Assistant Sunday School Teacher',
                'Team Member Choir Assistant',
                'Faith-Based Outreach Worker',
                'Intern Clothing Drive Volunteer',
                'Coordinator Church Usher',
                'Coordinator Mission Trip Volunteer',
                'Youth Group Leader',
                'Intern Community Prayer Partner',
                'Church Tech Support',
                'Intern Sunday School Teacher',
                'Volunteer Choir Assistant',
                'Intern Faith-Based Outreach Worker',
                'Coordinator Clothing Drive Volunteer',
                'Volunteer Church Usher',
                'Support Mission Trip Volunteer',
                'Team Member Youth Group Leader',
                'Intern Bible Study Assistant',
                'Lead Community Prayer Partner',
                'Assistant Church Tech Support',
                'Lead Sunday School Teacher',
                'Choir Assistant',
                'Assistant Faith-Based Outreach Worker',
                'Team Member Clothing Drive Volunteer',
                'Faith-Based & Mission Work-Other'
            ]
        ];

        foreach ($categories as $categoryName => $positions) {
            // Create or update the category
            $category = PositionCategory::updateOrCreate(
                ['name' => $categoryName],
                [
                    'description' => null,
                ]
            );

            // Add all positions for this category
            foreach ($positions as $positionTitle) {
                JobPosition::updateOrCreate(
                    [
                        'category_id' => $category->id,
                        'title' => $positionTitle
                    ],
                    [
                        'default_description' => 'This position is part of the ' . $categoryName . ' category.',
                        'default_requirements' => null
                    ]
                );
            }
        }
    }
}
