<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NteeCodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // A - Arts, Culture & Humanities
            ['ntee_code' => 'A01', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'A02', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'A03', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'A05', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'A11', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'A12', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'A19', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'A20', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Arts & Culture'],
            ['ntee_code' => 'A23', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Cultural & Ethnic Awareness'],
            ['ntee_code' => 'A25', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Arts Education'],
            ['ntee_code' => 'A26', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Arts & Humanities Councils & Agencies'],
            ['ntee_code' => 'A30', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Media & Communications'],
            ['ntee_code' => 'A31', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Film & Video'],
            ['ntee_code' => 'A32', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Television'],
            ['ntee_code' => 'A33', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Printing & Publishing'],
            ['ntee_code' => 'A34', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Radio'],
            ['ntee_code' => 'A40', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Visual Arts'],
            ['ntee_code' => 'A50', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Museums'],
            ['ntee_code' => 'A51', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Art Museums'],
            ['ntee_code' => 'A52', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Children\'s Museums'],
            ['ntee_code' => 'A54', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'History Museums'],
            ['ntee_code' => 'A56', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Natural History & Natural Science Museums'],
            ['ntee_code' => 'A57', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Science & Technology Museums'],
            ['ntee_code' => 'A60', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Performing Arts'],
            ['ntee_code' => 'A61', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Performing Arts Centers'],
            ['ntee_code' => 'A62', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Dance'],
            ['ntee_code' => 'A63', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Ballet'],
            ['ntee_code' => 'A65', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Theater'],
            ['ntee_code' => 'A68', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Music'],
            ['ntee_code' => 'A69', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Symphony Orchestras'],
            ['ntee_code' => 'A6A', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Opera'],
            ['ntee_code' => 'A70', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Humanities'],
            ['ntee_code' => 'A80', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Historical Societies & Related Activities'],
            ['ntee_code' => 'A84', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Commemorative Events'],
            ['ntee_code' => 'A90', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Arts Service Organizations & Activities'],
            ['ntee_code' => 'A99', 'major_group' => 'A', 'category' => 'Arts, Culture & Humanities', 'description' => 'Arts, Culture & Humanities N.E.C.'],

            // B - Education
            ['ntee_code' => 'B01', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'B02', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'B03', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'B05', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'B11', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'B12', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'B19', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'B20', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Elementary & Secondary Schools'],
            ['ntee_code' => 'B24', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Primary & Elementary Schools'],
            ['ntee_code' => 'B25', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Secondary & High Schools'],
            ['ntee_code' => 'B28', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Specialized Education Institutions'],
            ['ntee_code' => 'B30', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Vocational & Technical Schools'],
            ['ntee_code' => 'B40', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Higher Education Institutions'],
            ['ntee_code' => 'B41', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Community Colleges'],
            ['ntee_code' => 'B42', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Undergraduate Colleges'],
            ['ntee_code' => 'B43', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Universities'],
            ['ntee_code' => 'B50', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Graduate & Professional Schools'],
            ['ntee_code' => 'B60', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Adult & Continuing Education'],
            ['ntee_code' => 'B70', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Libraries'],
            ['ntee_code' => 'B80', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Student Services & Organizations'],
            ['ntee_code' => 'B82', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Scholarships & Financial Support'],
            ['ntee_code' => 'B83', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Student Sororities & Fraternities'],
            ['ntee_code' => 'B84', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Alumni Associations'],
            ['ntee_code' => 'B90', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Educational Services & Programs'],
            ['ntee_code' => 'B92', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Remedial Reading & Encouragement'],
            ['ntee_code' => 'B94', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Parent & Teacher Groups'],
            ['ntee_code' => 'B99', 'major_group' => 'B', 'category' => 'Education', 'description' => 'Education N.E.C.'],

            // C - Environment
            ['ntee_code' => 'C01', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'C02', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'C03', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'C05', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'C11', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'C12', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'C19', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'C20', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Pollution Abatement & Control'],
            ['ntee_code' => 'C27', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Recycling'],
            ['ntee_code' => 'C30', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Natural Resources Conservation & Protection'],
            ['ntee_code' => 'C32', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Water Resource, Wetlands Conservation & Management'],
            ['ntee_code' => 'C34', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Land Resources Conservation'],
            ['ntee_code' => 'C35', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Energy Resources Conservation & Development'],
            ['ntee_code' => 'C36', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Forest Conservation'],
            ['ntee_code' => 'C40', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Botanical, Horticultural & Landscape Services'],
            ['ntee_code' => 'C41', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Botanical Gardens & Arboreta'],
            ['ntee_code' => 'C42', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Garden Clubs & Horticultural Programs'],
            ['ntee_code' => 'C50', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Environmental Beautification & Aesthetics'],
            ['ntee_code' => 'C60', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Environmental Education & Outdoor Survival Programs'],
            ['ntee_code' => 'C99', 'major_group' => 'C', 'category' => 'Environment', 'description' => 'Environment N.E.C.'],

            // D - Animal-Related
            ['ntee_code' => 'D01', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'D02', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'D03', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'D05', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'D11', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'D12', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'D19', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'D20', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Animal Protection & Welfare'],
            ['ntee_code' => 'D30', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Wildlife Preservation & Protection'],
            ['ntee_code' => 'D31', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Protection of Endangered Species'],
            ['ntee_code' => 'D32', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Bird Sanctuaries'],
            ['ntee_code' => 'D33', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Fisheries'],
            ['ntee_code' => 'D34', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Wildlife Sanctuaries'],
            ['ntee_code' => 'D40', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Veterinary Services'],
            ['ntee_code' => 'D50', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Zoos & Aquariums'],
            ['ntee_code' => 'D60', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Other Services & Activities'],
            ['ntee_code' => 'D61', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Animal Training'],
            ['ntee_code' => 'D99', 'major_group' => 'D', 'category' => 'Animal-Related', 'description' => 'Animal-Related N.E.C.'],

            // E - Health Care
            ['ntee_code' => 'E01', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'E02', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'E03', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'E05', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'E11', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'E12', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'E19', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'E20', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Hospitals & Primary Medical Care Facilities'],
            ['ntee_code' => 'E21', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Community Health Systems'],
            ['ntee_code' => 'E22', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Hospital, General'],
            ['ntee_code' => 'E24', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Hospital, Specialty'],
            ['ntee_code' => 'E30', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Health Treatment Facilities & Primarily Outpatient Care'],
            ['ntee_code' => 'E31', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Group Health Practices'],
            ['ntee_code' => 'E32', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Ambulatory Health Center, Community Clinic'],
            ['ntee_code' => 'E40', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Reproductive Health Care Facilities & Allied Services'],
            ['ntee_code' => 'E42', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Family Planning Centers'],
            ['ntee_code' => 'E50', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Rehabilitative Medical Services'],
            ['ntee_code' => 'E60', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Health Support Services'],
            ['ntee_code' => 'E61', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Blood Supply Related'],
            ['ntee_code' => 'E62', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Ambulance & Emergency Medical Transport Services'],
            ['ntee_code' => 'E65', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Organ & Tissue Banks'],
            ['ntee_code' => 'E70', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Public Health Program'],
            ['ntee_code' => 'E80', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Health, General & Financing'],
            ['ntee_code' => 'E86', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Patient Services - Entertainment & Recreation'],
            ['ntee_code' => 'E90', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Nursing Services'],
            ['ntee_code' => 'E91', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Nursing, Convalescent Facilities'],
            ['ntee_code' => 'E92', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Home Health Care'],
            ['ntee_code' => 'E99', 'major_group' => 'E', 'category' => 'Health Care', 'description' => 'Health Care N.E.C.'],

            // F - Mental Health & Crisis Intervention
            ['ntee_code' => 'F01', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'F02', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'F03', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'F05', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'F11', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'F12', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'F19', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'F20', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Alcohol, Drug & Substance Abuse, Dependency Prevention & Treatment'],
            ['ntee_code' => 'F21', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Alcohol & Drug Abuse Prevention Only'],
            ['ntee_code' => 'F22', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Alcohol & Drug Abuse Treatment Only'],
            ['ntee_code' => 'F30', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Mental Health Treatment & Prevention'],
            ['ntee_code' => 'F31', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Psychiatric & Mental Health Hospitals'],
            ['ntee_code' => 'F32', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Community Mental Health Centers'],
            ['ntee_code' => 'F33', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Residential Mental Health Treatment'],
            ['ntee_code' => 'F40', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Hot Line & Crisis Intervention Services'],
            ['ntee_code' => 'F42', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Rape Victim Services'],
            ['ntee_code' => 'F50', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Addictive Disorders N.E.C.'],
            ['ntee_code' => 'F52', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Eating Disorders & Addiction'],
            ['ntee_code' => 'F53', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Gambling Addiction'],
            ['ntee_code' => 'F54', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Smoking Addiction'],
            ['ntee_code' => 'F60', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Counseling, Support Groups'],
            ['ntee_code' => 'F70', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Mental Health Disorders'],
            ['ntee_code' => 'F80', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Mental Health Association & Multipurpose Activities'],
            ['ntee_code' => 'F99', 'major_group' => 'F', 'category' => 'Mental Health & Crisis Intervention', 'description' => 'Mental Health & Crisis Intervention N.E.C.'],

            // G - Diseases, Disorders & Medical Disciplines
            ['ntee_code' => 'G01', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'G02', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'G03', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'G05', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'G11', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'G12', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'G19', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'G20', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Birth Defects & Genetic Diseases'],
            ['ntee_code' => 'G25', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Down Syndrome'],
            ['ntee_code' => 'G30', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Cancer'],
            ['ntee_code' => 'G40', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Diseases of Specific Organs'],
            ['ntee_code' => 'G41', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Eye Diseases, Blindness & Vision Impairments'],
            ['ntee_code' => 'G42', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Ear & Throat Diseases'],
            ['ntee_code' => 'G43', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Heart & Circulatory System Diseases, Disorders'],
            ['ntee_code' => 'G44', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Kidney Diseases'],
            ['ntee_code' => 'G45', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Lung & Respiratory Diseases'],
            ['ntee_code' => 'G48', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Brain Disorders'],
            ['ntee_code' => 'G50', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Nerve, Muscle & Bone Diseases'],
            ['ntee_code' => 'G51', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Arthritis'],
            ['ntee_code' => 'G54', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Epilepsy'],
            ['ntee_code' => 'G60', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Allergy Related Diseases'],
            ['ntee_code' => 'G61', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Asthma'],
            ['ntee_code' => 'G70', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Digestive Diseases, Disorders'],
            ['ntee_code' => 'G80', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Specifically Named Diseases'],
            ['ntee_code' => 'G81', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'AIDS'],
            ['ntee_code' => 'G83', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Alzheimer\'s Disease'],
            ['ntee_code' => 'G84', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Autism'],
            ['ntee_code' => 'G90', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Medical Disciplines'],
            ['ntee_code' => 'G92', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Biomedicine & Bioengineering'],
            ['ntee_code' => 'G94', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Geriatrics'],
            ['ntee_code' => 'G96', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Neurology, Neuroscience'],
            ['ntee_code' => 'G98', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Pediatrics'],
            ['ntee_code' => 'G99', 'major_group' => 'G', 'category' => 'Diseases, Disorders & Medical Disciplines', 'description' => 'Diseases, Disorders & Medical Disciplines N.E.C.'],

            // H - Medical Research
            ['ntee_code' => 'H01', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'H02', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'H03', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'H05', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'H11', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'H12', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'H19', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'H20', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Birth Defects & Genetic Diseases Research'],
            ['ntee_code' => 'H25', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Down Syndrome Research'],
            ['ntee_code' => 'H30', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Cancer Research'],
            ['ntee_code' => 'H40', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Diseases of Specific Organs Research'],
            ['ntee_code' => 'H41', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Eye Research'],
            ['ntee_code' => 'H42', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Ear & Throat Research'],
            ['ntee_code' => 'H43', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Heart & Circulatory System Research'],
            ['ntee_code' => 'H44', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Kidney Research'],
            ['ntee_code' => 'H45', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Lung & Respiratory Research'],
            ['ntee_code' => 'H48', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Brain Disorders Research'],
            ['ntee_code' => 'H50', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Nerve, Muscle & Bone Diseases Research'],
            ['ntee_code' => 'H51', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Arthritis Research'],
            ['ntee_code' => 'H54', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Epilepsy Research'],
            ['ntee_code' => 'H60', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Allergy Related Diseases Research'],
            ['ntee_code' => 'H61', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Asthma Research'],
            ['ntee_code' => 'H70', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Digestive Diseases & Disorders Research'],
            ['ntee_code' => 'H80', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Specifically Named Diseases Research'],
            ['ntee_code' => 'H81', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'AIDS Research'],
            ['ntee_code' => 'H83', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Alzheimer\'s Disease Research'],
            ['ntee_code' => 'H84', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Autism Research'],
            ['ntee_code' => 'H90', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Medical Disciplines Research'],
            ['ntee_code' => 'H92', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Biomedicine & Bioengineering Research'],
            ['ntee_code' => 'H94', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Geriatrics Research'],
            ['ntee_code' => 'H96', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Neurology, Neuroscience Research'],
            ['ntee_code' => 'H98', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Pediatrics Research'],
            ['ntee_code' => 'H99', 'major_group' => 'H', 'category' => 'Medical Research', 'description' => 'Medical Research N.E.C.'],

            // I - Crime & Legal Related
            ['ntee_code' => 'I01', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'I02', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'I03', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'I05', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'I11', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'I12', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'I19', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'I20', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Crime Prevention'],
            ['ntee_code' => 'I21', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Delinquency Prevention'],
            ['ntee_code' => 'I23', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Drunk Driving Related'],
            ['ntee_code' => 'I30', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Correctional Facilities & Related Activities'],
            ['ntee_code' => 'I31', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Juvenile Correctional Facilities'],
            ['ntee_code' => 'I40', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Rehabilitation Services for Offenders'],
            ['ntee_code' => 'I43', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Services to Prisoners & Families - Multipurpose'],
            ['ntee_code' => 'I44', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Prison Alternatives'],
            ['ntee_code' => 'I50', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Administration of Justice, Courts'],
            ['ntee_code' => 'I51', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Dispute Resolution & Mediation'],
            ['ntee_code' => 'I60', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Law Enforcement Agencies & Related Activities'],
            ['ntee_code' => 'I70', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Protection Against & Prevention of Neglect, Abuse, Exploitation'],
            ['ntee_code' => 'I71', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Spouse Abuse, Prevention of'],
            ['ntee_code' => 'I72', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Child Abuse, Prevention of'],
            ['ntee_code' => 'I73', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Sexual Abuse, Prevention of'],
            ['ntee_code' => 'I80', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Legal Services'],
            ['ntee_code' => 'I83', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Public Interest Law, Litigation'],
            ['ntee_code' => 'I99', 'major_group' => 'I', 'category' => 'Crime & Legal Related', 'description' => 'Crime & Legal Related N.E.C.'],

            // J - Employment
            ['ntee_code' => 'J01', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'J02', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'J03', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'J05', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'J11', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'J12', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'J19', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'J20', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Employment Procurement Assistance & Job Training'],
            ['ntee_code' => 'J21', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Vocational Counseling, Guidance & Testing'],
            ['ntee_code' => 'J22', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Vocational Training'],
            ['ntee_code' => 'J30', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Vocational Rehabilitation'],
            ['ntee_code' => 'J32', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Goodwill Industries'],
            ['ntee_code' => 'J33', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Sheltered Employment'],
            ['ntee_code' => 'J40', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Labor Unions, Organizations & Related Activities'],
            ['ntee_code' => 'J99', 'major_group' => 'J', 'category' => 'Employment', 'description' => 'Employment N.E.C.'],

            // K - Food, Agriculture & Nutrition
            ['ntee_code' => 'K01', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'K02', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'K03', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'K05', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'K11', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'K12', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'K19', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'K20', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Agricultural Programs'],
            ['ntee_code' => 'K25', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Farmland Preservation'],
            ['ntee_code' => 'K26', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Livestock Breeding, Development & Management'],
            ['ntee_code' => 'K28', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Rural Development'],
            ['ntee_code' => 'K30', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Food Programs'],
            ['ntee_code' => 'K31', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Food Banks, Food Pantries'],
            ['ntee_code' => 'K34', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Congregate Meals'],
            ['ntee_code' => 'K35', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Meals on Wheels'],
            ['ntee_code' => 'K36', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Food Distribution'],
            ['ntee_code' => 'K40', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Nutrition Programs'],
            ['ntee_code' => 'K99', 'major_group' => 'K', 'category' => 'Food, Agriculture & Nutrition', 'description' => 'Food, Agriculture & Nutrition N.E.C.'],

            // L - Housing & Shelter
            ['ntee_code' => 'L01', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'L02', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'L03', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'L05', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'L11', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'L12', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'L19', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'L20', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Housing Development, Construction & Management'],
            ['ntee_code' => 'L21', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Public Housing'],
            ['ntee_code' => 'L22', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Senior Citizens\' Housing & Retirement Communities'],
            ['ntee_code' => 'L25', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Housing Rehabilitation'],
            ['ntee_code' => 'L30', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Housing Search Assistance'],
            ['ntee_code' => 'L40', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Low-Cost Temporary Shelter'],
            ['ntee_code' => 'L41', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Homeless, Temporary Shelter For'],
            ['ntee_code' => 'L50', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Housing Owners, Renters Organizations'],
            ['ntee_code' => 'L80', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Housing Support Services'],
            ['ntee_code' => 'L81', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Home Improvement & Repairs'],
            ['ntee_code' => 'L82', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Housing Expense Reduction Support'],
            ['ntee_code' => 'L99', 'major_group' => 'L', 'category' => 'Housing & Shelter', 'description' => 'Housing & Shelter N.E.C.'],

            // M - Public Safety, Disaster Preparedness & Relief
            ['ntee_code' => 'M01', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'M02', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'M03', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'M05', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'M11', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'M12', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'M19', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'M20', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Disaster Preparedness & Relief Services'],
            ['ntee_code' => 'M23', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Search & Rescue Squads'],
            ['ntee_code' => 'M24', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Fire Prevention & Protection'],
            ['ntee_code' => 'M40', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Safety Education'],
            ['ntee_code' => 'M41', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'First Aid Training, Services'],
            ['ntee_code' => 'M42', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Automotive Safety'],
            ['ntee_code' => 'M99', 'major_group' => 'M', 'category' => 'Public Safety, Disaster Preparedness & Relief', 'description' => 'Public Safety, Disaster Preparedness & Relief N.E.C.'],

            // N - Recreation & Sports
            ['ntee_code' => 'N01', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'N02', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'N03', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'N05', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'N11', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'N12', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'N19', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'N20', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Recreational & Sporting Camps'],
            ['ntee_code' => 'N30', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Physical Fitness & Community Recreational Facilities'],
            ['ntee_code' => 'N31', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Community Recreational Centers'],
            ['ntee_code' => 'N32', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Parks & Playgrounds'],
            ['ntee_code' => 'N40', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Sports Training Facilities & Agencies'],
            ['ntee_code' => 'N50', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Recreational, Pleasure, or Social Club'],
            ['ntee_code' => 'N52', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Fairs, County & Other'],
            ['ntee_code' => 'N60', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Amateur Sports'],
            ['ntee_code' => 'N61', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Fishing & Hunting'],
            ['ntee_code' => 'N62', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Basketball'],
            ['ntee_code' => 'N63', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Baseball, Softball'],
            ['ntee_code' => 'N64', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Football'],
            ['ntee_code' => 'N65', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Soccer'],
            ['ntee_code' => 'N66', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Golf'],
            ['ntee_code' => 'N67', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Olympic & International Sports Competitions'],
            ['ntee_code' => 'N68', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Winter Sports'],
            ['ntee_code' => 'N69', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Water Sports'],
            ['ntee_code' => 'N70', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Other Amateur Sports Competitions'],
            ['ntee_code' => 'N71', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Olympic & International Sports Training'],
            ['ntee_code' => 'N72', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Special Olympics'],
            ['ntee_code' => 'N99', 'major_group' => 'N', 'category' => 'Recreation & Sports', 'description' => 'Recreation & Sports N.E.C.'],

            // O - Youth Development
            ['ntee_code' => 'O01', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'O02', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'O03', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'O05', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'O11', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'O12', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'O19', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'O20', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Youth Centers & Clubs'],
            ['ntee_code' => 'O21', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Boys Clubs'],
            ['ntee_code' => 'O22', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Girls Clubs'],
            ['ntee_code' => 'O23', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Boys & Girls Clubs'],
            ['ntee_code' => 'O30', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Adult & Child Matching Programs'],
            ['ntee_code' => 'O31', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Big Brothers & Big Sisters'],
            ['ntee_code' => 'O40', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Scouting Organizations'],
            ['ntee_code' => 'O41', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Boy Scouts of America'],
            ['ntee_code' => 'O42', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Girl Scouts of the U.S.A.'],
            ['ntee_code' => 'O43', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Camp Fire'],
            ['ntee_code' => 'O50', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Youth Development Programs'],
            ['ntee_code' => 'O51', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Youth Community Service Clubs'],
            ['ntee_code' => 'O52', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Youth Development - Agricultural'],
            ['ntee_code' => 'O53', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Youth Development - Business'],
            ['ntee_code' => 'O54', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Youth Development - Citizenship'],
            ['ntee_code' => 'O55', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Youth Development - Religious Leadership'],
            ['ntee_code' => 'O99', 'major_group' => 'O', 'category' => 'Youth Development', 'description' => 'Youth Development N.E.C.'],

            // P - Human Services
            ['ntee_code' => 'P01', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'P02', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'P03', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'P05', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'P11', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'P12', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'P19', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'P20', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Human Service Organizations'],
            ['ntee_code' => 'P21', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'American Red Cross'],
            ['ntee_code' => 'P22', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Urban League'],
            ['ntee_code' => 'P24', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Salvation Army'],
            ['ntee_code' => 'P26', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Volunteers of America'],
            ['ntee_code' => 'P27', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Young Men\'s Christian Associations'],
            ['ntee_code' => 'P28', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Young Women\'s Christian Associations'],
            ['ntee_code' => 'P29', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Other Religious Activities'],
            ['ntee_code' => 'P30', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Children & Youth Services'],
            ['ntee_code' => 'P31', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Adoption'],
            ['ntee_code' => 'P32', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Foster Care'],
            ['ntee_code' => 'P33', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Child Day Care'],
            ['ntee_code' => 'P40', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Family Services'],
            ['ntee_code' => 'P42', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Single Parent Agencies & Services'],
            ['ntee_code' => 'P43', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Family Violence Shelters & Services'],
            ['ntee_code' => 'P44', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'In-Home Assistance'],
            ['ntee_code' => 'P45', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Family Services, Counseling'],
            ['ntee_code' => 'P46', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Family Services, Adolescent Parents'],
            ['ntee_code' => 'P50', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Personal Social Services'],
            ['ntee_code' => 'P51', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Financial Counseling, Money Management'],
            ['ntee_code' => 'P52', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Transportation Assistance'],
            ['ntee_code' => 'P58', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Gift Distribution'],
            ['ntee_code' => 'P60', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Emergency Assistance'],
            ['ntee_code' => 'P61', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Travelers\' Aid'],
            ['ntee_code' => 'P62', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Victims\' Services'],
            ['ntee_code' => 'P70', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Residential, Custodial Care'],
            ['ntee_code' => 'P73', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Group Homes'],
            ['ntee_code' => 'P74', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Homes for the Aging'],
            ['ntee_code' => 'P75', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Homes for People with Mental Disabilities'],
            ['ntee_code' => 'P80', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Services to Promote the Independence of Specific Populations'],
            ['ntee_code' => 'P81', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Senior Centers, Services'],
            ['ntee_code' => 'P82', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Developmentally Disabled Services & Centers'],
            ['ntee_code' => 'P84', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Ethnic & Immigrant Centers & Services'],
            ['ntee_code' => 'P85', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Homeless Persons Centers & Services'],
            ['ntee_code' => 'P86', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Blind & Visually Impaired Centers & Services'],
            ['ntee_code' => 'P87', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Deaf & Hearing Impaired Centers & Services'],
            ['ntee_code' => 'P99', 'major_group' => 'P', 'category' => 'Human Services', 'description' => 'Human Services N.E.C.'],

            // Q - International, Foreign Affairs & National Security
            ['ntee_code' => 'Q01', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'Q02', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'Q03', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'Q05', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'Q11', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'Q12', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'Q19', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'Q20', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'Promotion of International Understanding'],
            ['ntee_code' => 'Q21', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Cultural Exchange'],
            ['ntee_code' => 'Q22', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Student Exchange & Aid'],
            ['ntee_code' => 'Q23', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Exchange N.E.C.'],
            ['ntee_code' => 'Q30', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Development, Relief Services'],
            ['ntee_code' => 'Q31', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Economic Development'],
            ['ntee_code' => 'Q32', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Agricultural Development'],
            ['ntee_code' => 'Q33', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Relief'],
            ['ntee_code' => 'Q40', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Peace & Security'],
            ['ntee_code' => 'Q41', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'Arms Control & Peace'],
            ['ntee_code' => 'Q42', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'National Security'],
            ['ntee_code' => 'Q43', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'U.S. Department of State'],
            ['ntee_code' => 'Q50', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Affairs, Foreign Policy'],
            ['ntee_code' => 'Q70', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International Human Rights'],
            ['ntee_code' => 'Q99', 'major_group' => 'Q', 'category' => 'International, Foreign Affairs & National Security', 'description' => 'International, Foreign Affairs & National Security N.E.C.'],

            // R - Civil Rights, Social Action & Advocacy
            ['ntee_code' => 'R01', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'R02', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'R03', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'R05', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'R11', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'R12', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'R19', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'R20', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Civil Rights'],
            ['ntee_code' => 'R22', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Minority Rights'],
            ['ntee_code' => 'R24', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Women\'s Rights'],
            ['ntee_code' => 'R25', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Senior Rights'],
            ['ntee_code' => 'R26', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Lesbian, Gay, Bisexual & Transgender Rights'],
            ['ntee_code' => 'R30', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Intergroup & Race Relations'],
            ['ntee_code' => 'R40', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Voter Education & Registration'],
            ['ntee_code' => 'R50', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Social Action & Advocacy N.E.C.'],
            ['ntee_code' => 'R60', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Civil Liberties'],
            ['ntee_code' => 'R61', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Reproductive Rights'],
            ['ntee_code' => 'R62', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Right to Life'],
            ['ntee_code' => 'R63', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Censorship, Freedom of Speech & Press'],
            ['ntee_code' => 'R67', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Immigrants\' Rights'],
            ['ntee_code' => 'R99', 'major_group' => 'R', 'category' => 'Civil Rights, Social Action & Advocacy', 'description' => 'Civil Rights, Social Action & Advocacy N.E.C.'],

            // S - Community Improvement & Capacity Building
            ['ntee_code' => 'S01', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'S02', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'S03', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'S05', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'S11', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'S12', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'S19', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'S20', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Community & Neighborhood Development'],
            ['ntee_code' => 'S21', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Community Coalitions'],
            ['ntee_code' => 'S22', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Neighborhood & Block Associations'],
            ['ntee_code' => 'S30', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Economic Development'],
            ['ntee_code' => 'S31', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Urban & Community Economic Development'],
            ['ntee_code' => 'S32', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Rural Development'],
            ['ntee_code' => 'S33', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Indian Development'],
            ['ntee_code' => 'S34', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Small Business Development'],
            ['ntee_code' => 'S40', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Business & Industry'],
            ['ntee_code' => 'S41', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Promotion of Business'],
            ['ntee_code' => 'S42', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Management Services for Small Business, Entrepreneurs'],
            ['ntee_code' => 'S43', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Small Business Credit & Lending Organizations'],
            ['ntee_code' => 'S44', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Small Business Assistance'],
            ['ntee_code' => 'S45', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Real Estate Owners & Developers'],
            ['ntee_code' => 'S46', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Board of Trade'],
            ['ntee_code' => 'S47', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Real Estate Associations'],
            ['ntee_code' => 'S50', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Nonprofit Management'],
            ['ntee_code' => 'S80', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Community Service Clubs'],
            ['ntee_code' => 'S81', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Women\'s Service Clubs'],
            ['ntee_code' => 'S82', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Men\'s Service Clubs'],
            ['ntee_code' => 'S99', 'major_group' => 'S', 'category' => 'Community Improvement & Capacity Building', 'description' => 'Community Improvement & Capacity Building N.E.C.'],

            // T - Philanthropy, Voluntarism & Grantmaking Foundations
            ['ntee_code' => 'T01', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'T02', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'T03', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'T05', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'T11', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'T12', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'T19', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'T20', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Private Grantmaking Foundations'],
            ['ntee_code' => 'T21', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Corporate Foundations'],
            ['ntee_code' => 'T22', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Private Independent Foundations'],
            ['ntee_code' => 'T23', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Private Operating Foundations'],
            ['ntee_code' => 'T30', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Public Foundations'],
            ['ntee_code' => 'T31', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Community Foundations'],
            ['ntee_code' => 'T40', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Voluntarism Promotion'],
            ['ntee_code' => 'T50', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Philanthropy, Charity, Voluntarism Promotion, General'],
            ['ntee_code' => 'T70', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Federated Giving Programs'],
            ['ntee_code' => 'T90', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Named Trusts/Foundations N.E.C.'],
            ['ntee_code' => 'T99', 'major_group' => 'T', 'category' => 'Philanthropy, Voluntarism & Grantmaking Foundations', 'description' => 'Philanthropy, Voluntarism & Grantmaking Foundations N.E.C.'],

            // U - Science & Technology
            ['ntee_code' => 'U01', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'U02', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'U03', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'U05', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'U11', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'U12', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'U19', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'U20', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Science & Technology, General'],
            ['ntee_code' => 'U21', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Marine Science & Oceanography'],
            ['ntee_code' => 'U22', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Computer Science'],
            ['ntee_code' => 'U30', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Physical & Earth Sciences'],
            ['ntee_code' => 'U31', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Astronomy'],
            ['ntee_code' => 'U32', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Mathematics'],
            ['ntee_code' => 'U33', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Chemistry'],
            ['ntee_code' => 'U34', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Physics'],
            ['ntee_code' => 'U35', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Geology'],
            ['ntee_code' => 'U40', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Engineering & Technology'],
            ['ntee_code' => 'U41', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Electrical Engineering'],
            ['ntee_code' => 'U42', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Engineering'],
            ['ntee_code' => 'U43', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Mechanical Engineering'],
            ['ntee_code' => 'U50', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Biological & Life Sciences'],
            ['ntee_code' => 'U99', 'major_group' => 'U', 'category' => 'Science & Technology', 'description' => 'Science & Technology N.E.C.'],

            // V - Social Science
            ['ntee_code' => 'V01', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'V02', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'V03', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'V05', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'V11', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'V12', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'V19', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'V20', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Social Science'],
            ['ntee_code' => 'V21', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Anthropology & Sociology'],
            ['ntee_code' => 'V22', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Economics'],
            ['ntee_code' => 'V23', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Behavioral Science'],
            ['ntee_code' => 'V24', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Psychology'],
            ['ntee_code' => 'V25', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Political Science'],
            ['ntee_code' => 'V26', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Law & Jurisprudence'],
            ['ntee_code' => 'V30', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Interdisciplinary Research'],
            ['ntee_code' => 'V31', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'International Studies'],
            ['ntee_code' => 'V32', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Urban & Metropolitan Studies'],
            ['ntee_code' => 'V33', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Women\'s Studies'],
            ['ntee_code' => 'V34', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Ethnic & Minority Studies'],
            ['ntee_code' => 'V35', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Population Studies'],
            ['ntee_code' => 'V36', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Gerontology'],
            ['ntee_code' => 'V37', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Future Studies'],
            ['ntee_code' => 'V99', 'major_group' => 'V', 'category' => 'Social Science', 'description' => 'Social Science N.E.C.'],

            // W - Public & Societal Benefit
            ['ntee_code' => 'W01', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'W02', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'W03', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'W05', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'W11', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'W12', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'W19', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'W20', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Government & Public Administration'],
            ['ntee_code' => 'W22', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Public Finance, Taxation & Monetary Policy'],
            ['ntee_code' => 'W24', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Citizen Participation'],
            ['ntee_code' => 'W30', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Military & Veterans\' Organizations'],
            ['ntee_code' => 'W40', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Public Transportation Systems & Services'],
            ['ntee_code' => 'W50', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Telecommunications & Broadcasting'],
            ['ntee_code' => 'W60', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Financial Institutions & Services'],
            ['ntee_code' => 'W61', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Credit Unions'],
            ['ntee_code' => 'W70', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Leadership Development'],
            ['ntee_code' => 'W80', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Public Utilities'],
            ['ntee_code' => 'W90', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Consumer Protection, Safety & Education'],
            ['ntee_code' => 'W99', 'major_group' => 'W', 'category' => 'Public & Societal Benefit', 'description' => 'Public & Societal Benefit N.E.C.'],

            // X - Religion Related
            ['ntee_code' => 'X01', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'X02', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'X03', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'X05', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'X11', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'X12', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'X19', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'X20', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Christian'],
            ['ntee_code' => 'X21', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Protestant'],
            ['ntee_code' => 'X22', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Roman Catholic'],
            ['ntee_code' => 'X30', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Jewish'],
            ['ntee_code' => 'X40', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Islamic'],
            ['ntee_code' => 'X50', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Buddhist'],
            ['ntee_code' => 'X70', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Interfaith Issues'],
            ['ntee_code' => 'X80', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Religious Leadership'],
            ['ntee_code' => 'X81', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Religious Education'],
            ['ntee_code' => 'X82', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Theological Seminaries & Related Schools'],
            ['ntee_code' => 'X83', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Religious Media & Communications'],
            ['ntee_code' => 'X84', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Religious Activities in Higher Education'],
            ['ntee_code' => 'X85', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Religious Centers & Services'],
            ['ntee_code' => 'X99', 'major_group' => 'X', 'category' => 'Religion Related', 'description' => 'Religion Related N.E.C.'],

            // Y - Mutual & Membership Benefit
            ['ntee_code' => 'Y01', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Alliances & Advocacy'],
            ['ntee_code' => 'Y02', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Management & Technical Assistance'],
            ['ntee_code' => 'Y03', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Professional Societies & Associations'],
            ['ntee_code' => 'Y05', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Research Institutes & Public Policy Analysis'],
            ['ntee_code' => 'Y11', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Single Organization Support'],
            ['ntee_code' => 'Y12', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Fund Raising & Fund Distribution'],
            ['ntee_code' => 'Y19', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Nonmonetary Support N.E.C.'],
            ['ntee_code' => 'Y20', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Private, Independent Foundations'],
            ['ntee_code' => 'Y21', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Corporate Foundations'],
            ['ntee_code' => 'Y22', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Private Operating Foundations'],
            ['ntee_code' => 'Y23', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Community Foundations'],
            ['ntee_code' => 'Y24', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Federated Giving Programs'],
            ['ntee_code' => 'Y25', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Other Named Trusts/Foundations'],
            ['ntee_code' => 'Y30', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Pension & Retirement Funds'],
            ['ntee_code' => 'Y33', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Mutual Insurance, Benevolent & Fraternal Benefit Societies'],
            ['ntee_code' => 'Y34', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Voluntary Employees\' Beneficiary Associations (Non-Government)'],
            ['ntee_code' => 'Y35', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Voluntary Employees\' Beneficiary Associations (Government)'],
            ['ntee_code' => 'Y40', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Fraternal Beneficiary Societies'],
            ['ntee_code' => 'Y41', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Fraternal Societies'],
            ['ntee_code' => 'Y42', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Domestic Fraternal Societies'],
            ['ntee_code' => 'Y43', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Women\'s Auxiliaries & Federations'],
            ['ntee_code' => 'Y44', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Cemeteries & Burial Services'],
            ['ntee_code' => 'Y50', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Civic & Social Associations'],
            ['ntee_code' => 'Y51', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Chambers of Commerce & Business Leagues'],
            ['ntee_code' => 'Y52', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Real Estate Organizations'],
            ['ntee_code' => 'Y53', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Homeowners & Tenants Associations'],
            ['ntee_code' => 'Y54', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Condominium & Cooperative Associations'],
            ['ntee_code' => 'Y55', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Veterans\' Membership Organizations'],
            ['ntee_code' => 'Y99', 'major_group' => 'Y', 'category' => 'Mutual & Membership Benefit', 'description' => 'Mutual & Membership Benefit N.E.C.'],

            // Z - Unknown / Unclassified
            ['ntee_code' => 'Z99', 'major_group' => 'Z', 'category' => 'Unknown / Unclassified', 'description' => 'Unknown or unclassified nonprofit purpose'],
        ];

        foreach ($data as $item) {
            DB::table('ntee_codes')->updateOrInsert(
                ['ntee_codes' => $item['ntee_code']],
                [
                    // 'major_group' => $item['major_group'],
                    'category' => $item['category'],
                    'description' => $item['description'],
                    'created_at' => now(),
                    'updated_at' => now()
                ]
            );
        }
    }
}
