name: Build and deploy Laravel to Azure Web App - believe-cash

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      PHP_VERSION: '8.3'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
          extensions: mbstring, intl, bcmath, ctype, curl, dom, fileinfo, json, openssl, pdo, pdo_mysql, tokenizer, xml

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install PHP dependencies (prod)
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          # Ensure view dirs exist so view:cache doesn't fail
          mkdir -p resources/views
          mkdir -p storage/framework/views
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache


      # If you use Vite/Node assets, build them
      - name: Setup Node
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend (if present)
        if: hashFiles('package.json') != ''
        run: |
          npm ci
          npm run build

      # Ensure root .htaccess exists to route to /public
      - name: Ensure root .htaccess
        run: |
          if [ ! -f .htaccess ]; then
            cat > .htaccess <<'HTACCESS'
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteRule ^index\.php$ - [L]
            RewriteCond %{REQUEST_URI} !^/public/
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule ^(.*)$ public/$1 [L]
          </IfModule>
          HTACCESS
          fi

      # Package a clean artifact for Zip Deploy
      - name: Create deployment package
        run: |
          rm -f app.zip
          zip -r app.zip . \
            -x ".git/*" ".github/*" "tests/*" "node_modules/*" "storage/logs/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app-zip
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app-zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: believe-cash
          slot-name: Production
          package: app.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3D1C832605F1410F9AF04E1576811AE7 }}

